### ISSUE TITLE
AWS SDK Not Working On Android With Unity 2019.1.0f2

### ISSUE THREAD

**Issue by daltonmachado** [aws/aws-sdk-net#1286]
Hello guys. I'm getting the same errors described in #1262 but I'm getting those when trying to call a Lambda function with `Amazon.Lambda.AmazonLambdaClient.InvokeAsync`.

Just to make clear: this issue is happening in Android builds with Unity 2019.1.0f2. The AWS plugin works fine in the Unity Editor.

## Expected Behavior

The callback method passed to `Amazon.Lambda.AmazonLambdaClient.InvokeAsync` should get called when the response is received.

## Current Behavior

The callback method passed to `Amazon.Lambda.AmazonLambdaClient.InvokeAsync` never gets called and the following errors are thrown:
```
Error Unity Unable to find /usr/lib/libobjc.dylib
Error Unity ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
Error Unity at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in <a6266edc72ee4a578659208aefcdd5e1>:0 
Error Unity at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00069] in <a6266edc72ee4a578659208aefcdd5e1>:0 
Error Unity at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in <a6266edc72ee4a578659208aefcdd5e1>:0 
Error Unity at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <a6266edc72ee4a578659208aefcdd5e1>:0 
Error Unity a
```

## Possible Solution

I've submitted a bug report to Unity's support with an example project and they were able identify the source of the issue. They did some design changes in Unity 2019 that break the AWS plugin code. Bellow is the answer I got from them describing the issue:

> Hi! 
> 
> The error you are seeing is caused by incorrect use of reflection in the AWS plugin: 
> https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L59 
> 
> In particular, line 71 (which finds the method) was used to find and call the method with the signature 
> 
> (1) public ReturnType CallStatic<ReturnType>(string methodName, params object[] args) 
> 
> In Unity 2019.1, to improve support for passing an array to the methods, we added few new methods to AndroidJavaObject, among them: 
> 
> (2) public void CallStatic<T>(string methodName, T[] args) 
> (3) public ReturnType CallStatic<ReturnType, T>(string methodName, T[] args) 
> 
> The plugin wants to find a method which returns AndroidJavaObject (signature (1), see call to MakeGenericMethod()), but now it finds method (2) where T: AndroidJavaObject. This method expects AndroidJavaObject[] as a param, but it gets object[] so you get your error. 
> 
> The fix for the issue should be done on AWS SDK side, by updating the LINQ query to find the method. Please submit a bug report on Github, feel free to include the info I posted here. 
> 
> I'm closing this bug as "By design". 
> 
> Regards 
> Yury Habets

Can anyone please verify (and hopefully fix) this? Thanks in advance.

## Steps to Reproduce (for bugs)

Just call `Amazon.Lambda.AmazonLambdaClient.InvokeAsync` and you see that the callback never gets called and some errors are thrown. Actually, this issue affects all async methods in the SDK, another example would be `Amazon.S3.AmazonS3Client.ListObjectsAsync`.

## Context

Below is the only script I've included in the example project I submitted to Unity:

```csharp
using System.Text;
using Amazon;
using Amazon.Lambda;
using Amazon.Lambda.Model;
using UnityEngine;
using UnityEngine.UI;

public class AmazonLambdaFunctionInvoker : MonoBehaviour {
    [SerializeField] string region;
    [SerializeField] string functionName;
    [SerializeField] string functionPayload;
    [SerializeField] string accessKey;
    [SerializeField] string secretKey;

    [SerializeField] Text logText;
	
    void Awake() {
        logText.text = string.Format("[ Built with Unity {0} ]\n\n", Application.unityVersion);

	UnityInitializer.AttachToGameObject(gameObject);
	logText.text += "AWS Plugin Initialized.\n";

	AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;
	logText.text += "AWS HTTP Client set to UnityWebRequest.\n";
    }

    void Start() {
	AmazonLambdaClient client = new AmazonLambdaClient(accessKey, secretKey, RegionEndpoint.GetBySystemName(region));
		
        using (client) {
            logText.text += string.Format("Invoking {0}('{1}')...\n", functionName, functionPayload);
			
	    client.InvokeAsync(new InvokeRequest() { FunctionName = functionName, Payload = functionPayload }, (responseObject) => {
		logText.text += "Lambda response received.\n";
				
		if (responseObject.Exception != null) {
		    logText.text += "ERROR: " + responseObject.Exception.Message + '\n';
		    return;
		}

		float result;
		float.TryParse(Encoding.ASCII.GetString(responseObject.Response.Payload.ToArray()), out result);
				
		logText.text += "Function result: " + result + '\n';	
	    });
        }
    }
}

```

## Your Environment

* AWSSDK.Core version used: 3.3.500.0
* Operating System and version: Windows Unity Editor 2019.1.0f2 building app to Android

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
This seems like a duplicate of https://github.com/aws/aws-sdk-net/issues/1262?

**Comment by daltonmachado** [comment]
It's not a duplicate. I've read the entire report and comments of #1262 and a proper fix was not made, only a workaround was achieved by the OP. And the real source of the issue was never pointed out.

My report shows the exact source of the issue and the possible fix pointed out by Unity's support team, it is clearly described in the **Possible Solution** section. Isn't that correct?

**Comment by sstevenkang** [comment]
Are you using the legacy Unity flavor of the SDK or the netstandard2.0 version of the full .NET SDK?  Unity versions newer than 2018.1 should be able to build against netstandard2.0 dlls.  The guidance we provided in #1262 is that Unity apps should build against the full version of .NET SDK and, specifically, against the netstandard2.0 version of the dlls.

**Comment by daltonmachado** [comment]
I'm using the Unity Packages accessible through [here](https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md). Since it's linked in the front page of this repo, I'm assuming those packages are the release-plug-and-play versions to be used and those worked fine in many Android apps I made with Unity until 2019.1. I don't know if those packages use netstandard2.0.

Did you read the email by Unity in the Possible Solution section? They made some changes to the Android part of Unity in 2019.1 and those changes break the current code in [AndroidInterop.cs](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L71) (which is from 4 years ago). My question here is: isn't that correct what was pointed out by the Unity team? The fix they proposed wouldn't work and make the Unity Packages plug & play again?

**Comment by daltonmachado** [comment]
I've managed to fix the issue. I cloned the repo, opened the AWSSDK.Unity Solution, added the UnityEngine.dll reference through NuGet and fixed the wrong lines in AndroidInterop.cs to finally build the AWSSDK.Lambda.Unity project to get the fixed DLLs. I don't know if the NuGet referencing method is the right one, I was not able to reference my local UnityEngine.dll.

Here is what I did to fix the code:

As pointed out by Yury (from Unity support), they added new methods to `AndroidJavaObject` in Unity 2019.1. Before that there was only one possible result for the LINQ query in [line 71 of AndroidInterop.cs](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L71), which was `ReturnType CallStatic<ReturnType>(System.String, System.Object[])`, but now the `Where()` clause of the query returns three methods:
```
Void CallStatic<T>(System.String, T[])
ReturnType CallStatic<ReturnType,T>(System.String, T[])
ReturnType CallStatic<ReturnType>(System.String, System.Object[])
```
Those methods are returned in the same order above, so our desired method is no longer accessible by the `First()` clause in the LINQ query. Our method is now the third and last one, not the first. The same issue also happens in lines [92](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L92), [107](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L107) and [172](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs#L172).

To fix that I simply replaced the `First()` clause in the wrong queries for `Last()`. That doesn't seem to be a good solution because Unity could add or remove methods in the future and change the returning order of the query again. I think the ultimate solution would be a query to pinpoint the exact method signature we need and don't rely on the order of the results. I don't know how to do that, it's the first time I have to deal with this reflection stuff. I think it's possible though, let me know how please.

I don't know what is the process now. Will you guys put that fix on the roadmap?

**Comment by kvasukib** [comment]
@daltonmachado Thank you for the detailed analysis on this issue. Is it possible for you to submit a Pull Request for the fix that you have implemented and tested?

**Comment by daltonmachado** [comment]
Hello @kvasukib. As I mentioned, my fix isn't ideal because it still relies on the returning order of the LINQ query. I'll try something like [this](https://stackoverflow.com/a/5152508) later and I'll submit a Pull Request if it works. If someone else have a better solution to this, please let us know here.

**Comment by daltonmachado** [comment]
Alright, I got the time to properly fix the issue. I tried a LINQ query based on the link in my previous post. I replaced line 71 of AndroidInterop.cs for this:
```csharp
var callStaticMethod = androidJavaClassType.GetMethods().Where(x => x.Name == "CallStatic").First(x =>
    x.ContainsGenericParameters &&
    x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new Type[] { typeof(string), typeof(object[]) })
);
```
I made similar queries for the other lines I mentioned previously and it worked. Now the queries find the method signatures with the specific parameters sequences we want and the queries don't rely on the returning order anymore because only one method is returned by each query.

I'll submit a Pull Request.

**Comment by bilck** [comment]
> Alright, I got the time to properly fix the issue. I tried a LINQ query based on the link in my previous post. I replaced line 71 of AndroidInterop.cs for this:
> 
> ```cs
> var callStaticMethod = androidJavaClassType.GetMethods().Where(x => x.Name == "CallStatic").First(x =>
>     x.ContainsGenericParameters &&
>     x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new Type[] { typeof(string), typeof(object[]) })
> );
> ```
> 
> I made similar queries for the other lines I mentioned previously and it worked. Now the queries find the method signatures with the specific parameters sequences we want and the queries don't rely on the returning order anymore because only one method is returned by each query.
> 
> I'll submit a Pull Request.

Worked like a charm.
Copied AndroidInterop class content from your version at this link: https://github.com/aws/aws-sdk-net/blob/af307ffcd7dd3ba78c2b185bb10e6bf1738ddaaf/sdk/src/Core/Amazon.Util/Internal/_unity/AndroidInterop.cs

Thanks!

**Comment by sampaiodias** [comment]
Please, could somebody provide a DLL that works for the current SDK? If you can't, the AWSSDK folder (Core, S3, etc.) that works for your project can also save me too

**Comment by left-brain** [comment]
PLEASE merge the pull request, I really need the aws sdk, it's not working on Android.

**Comment by left-brain** [comment]
@daltonmachado I can't compile the project to generate the dlls, can you help me?

**Comment by Gabana** [comment]
IF you need the DLL , here's it. Just translate the webpage as it is in Korean.
http://today7e.blogspot.com/2019/07/unity-android-aws-sdk-unity-2019-error.html

**Comment by left-brain** [comment]
> IF you need the DLL , here's it. Just translate the webpage as it is in Korean.
> http://today7e.blogspot.com/2019/07/unity-android-aws-sdk-unity-2019-error.html

Thanks, I had managed to compile the latest version myself, it works perfectly. I'm just worried about the other users, this is very inconvenient. It looks like sdk is abandoned for Unity, while Firebase Database probably wouldn't have this problem.

**Comment by Gabana** [comment]
> > IF you need the DLL , here's it. Just translate the webpage as it is in Korean.
> > http://today7e.blogspot.com/2019/07/unity-android-aws-sdk-unity-2019-error.html
> 
> Thanks, I had managed to compile the latest version myself, it works perfectly. I'm just worried about the other users, this is very inconvenient. It looks like sdk is abandoned for Unity, while Firebase Database probably wouldn't have this problem.

Great, can you please share your solution too, just in case....

**Comment by iankarasz** [comment]
I would also be interested in seeing your solution. I tried a few dll's that I've seen posted and I end up getting this error:

`E/Unity: TypeLoadException: Could not load type of field 'Amazon.SecurityToken.AmazonSecurityTokenServiceConfig:<StsRegionalEndpoints>k__BackingField' (0) due to: Could not resolve type with token 0100002a (from typeref, class/assembly Amazon.Runtime.StsRegionalEndpointsValue, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null) assembly:AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null type:Amazon.Runtime.StsRegionalEndpointsValue member:(null) signature:<none>
      at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor (System.String accountId, System.String identityPoolId, System.String unAuthRoleArn, System.String authRoleArn, Amazon.RegionEndpoint region) [0x00017] in <a0afd534d77f4c8ebd0c1d004e7b7b27>:0 
      at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor (System.String identityPoolId, Amazon.RegionEndpoint region) [0x00000] in <a0afd534d77f4c8ebd0c1d004e7b7b27>:0 
      at LambdaService.get_Credentials () [0x00015] in <7e7a86cace5a404c9dd13906b7ae2d7a>:0 
      at LambdaService.get_Clie`

I'm assuming this might be because the versions of the sdk and the dll are out of sync?
I tried compiling the dll myself by pulling the solution and adding the fix then building the AWSSDK.core.unity project. I get no errors but the dll still won't show up in the bin folder.  

Has anyone tried anything else that worked for them?

**Comment by AQ1991** [comment]
Same issue i am using AWS S3 sdk version 3.3.110.19 the latest sdk provided on the amazon website i get the same errors, i have tried everything nothing works, the funny this is the sdk work good in editor but when i build it for android i get these exceptions. 
using **Unity 2019.2.7f2**
Building for **Arm7** & **Arm64**
**OpenJDK**, **SDK** & **NDK** tried on Unity Hub provided and manually downloaded same issue exists
Waiting for some one to help i have worked on this project way to long to scrap it.

Logs:
> Error Unity Unable to find /usr/lib/libobjc.dylib
> Error Unity ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
> Error Unity at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in <a6266edc72ee4a578659208aefcdd5e1>:0 
> Error Unity at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00069] in <a6266edc72ee4a578659208aefcdd5e1>:0 
> Error Unity at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in <a6266edc72ee4a578659208aefcdd5e1>:0 
> Error Unity at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <a6266edc72ee4a578659208aefcdd5e1>:0 
> Error Unity a

**Comment by zerozinczero** [comment]
I was having trouble building a .DLL too, but I just got it to work now. I went to Tools -> Options -> Tools for Unity -> and changed "Disable the Full build of Projects" from "True" to "False". Doing this allows the project to make a full build and create a .DLL, just in case anyone is still wondering why they can't generate a .DLL

**Comment by zerozinczero** [comment]
> Same issue i am using AWS S3 sdk version 3.3.110.19 the latest sdk provided on the amazon website i get the same errors, i have tried everything nothing works, the funny this is the sdk work good in editor but when i build it for android i get these exceptions.
> using **Unity 2019.2.7f2**
> Building for **Arm7** & **Arm64**
> **OpenJDK**, **SDK** & **NDK** tried on Unity Hub provided and manually downloaded same issue exists
> Waiting for some one to help i have worked on this project way to long to scrap it.
> 
> Logs:
> 
> > Error Unity Unable to find /usr/lib/libobjc.dylib
> > Error Unity ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
> > Error Unity at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in :0
> > Error Unity at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00069] in :0
> > Error Unity at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in :0
> > Error Unity at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in :0
> > Error Unity a

Can you share your AndroidManifest? Whenever I build my app it immediately closes. I think it's because of the Android manifest being changed by the AWSSDK.Polly unity project i'm importing.

**Comment by zerozinczero** [comment]
> Error Unity Unable to find /usr/lib/libobjc.dylib

@ AQ1991 try what I did above to generate a .DLL and then replace the AWSSDK.Core.DLL with the one you made. That should fix the System.Object[] error... however I still haven't found a fix for /usr/lib/libobjc.dylib. Hope that helps

**Comment by AQ1991** [comment]
@zerozinczero still can't find tools on my editor, i am using 2019.2 maybe that's the issue.

**Comment by zerozinczero** [comment]
@AQ1991 Sorry, I may have skipped a few steps. Once you download the pull request and open the AWSSDK Unity Solution in Visual Studio ( not Unity), then go to Tools -> Options -> Tools for Unity -> and changed "Disable the Full build of Projects" from "True" to "False". Doing this allows the project to make a full build and create a .DLL, just in case anyone is still wondering why they can't generate a .DLL. 

It sounds like you were trying to do this through Unity, when I did this by just opening the Visual Studio Unity Solution. 

Once you've done this, remove the old AWSSDK.Core from Unity (It may be in your Assets Folder and if not, open your C# project by right clicking in the Assets folder and then looking in the References section of your Solution Explorer and removing it from there)  and then drag in the AWSSDK.Core.dll you created into the Assets folder. That should work.

**Comment by zerozinczero** [comment]
@daltonmachado how were you able to fix this error:

Error Unity Unable to find /usr/lib/libobjc.dylib

I followed this forum and your instructions, and I got the System.Object[] error to go away, but the AWSSDK.dll that I generated did not fix the libobjc.dylib error. I'm also confused as to why we're getting this error since .dylib files are dynamic linked libraries for Mac and not Windows.

**Comment by AQ1991** [comment]
> @AQ1991 Sorry, I may have skipped a few steps. Once you download the pull request and open the AWSSDK Unity Solution in Visual Studio ( not Unity), then go to Tools -> Options -> Tools for Unity -> and changed "Disable the Full build of Projects" from "True" to "False". Doing this allows the project to make a full build and create a .DLL, just in case anyone is still wondering why they can't generate a .DLL.
> 
> It sounds like you were trying to do this through Unity, when I did this by just opening the Visual Studio Unity Solution.
> 
> Once you've done this, remove the old AWSSDK.Core from Unity (It may be in your Assets Folder and if not, open your C# project by right clicking in the Assets folder and then looking in the References section of your Solution Explorer and removing it from there) and then drag in the AWSSDK.Core.dll you created into the Assets folder. That should work.

Ok will try it in future but currently found a work around to the problem. My work around was that i able to get public downloadable link for a limited time like for about 1 min max then i just send a simple HTTP request to download the file.

**Comment by zerozinczero** [comment]
@AQ1991 what downloadable link? Could you share it to see if it fixes my issue?

**Comment by zerozinczero** [comment]
In case anyone was still getting this error: "Error Unity Unable to find /usr/lib/libobjc.dylib", I found a "fix" for it for Windows/Android

The .dylib file is for dynamic linked library iOS and as a result is unneeded for a Windows or Android build. Within AWSSDK.Core project go to  Amazon.Util -> _unity -> AmazonHookedPlatformInfo file and comment out ThirdParty.iOS4Unity. This folder has code that calls the error and shouldn't be needed for non iOS builds. Comment out the rest of the code in AmazonHookedPlatformInfo that uses iOS4Unity and then build the AWSSDK.Core project. replace the old AWSSDK.Core.dll with the new one you generated and  that should remove the /usr/lib/libobjc.dylib error

**Comment by AQ1991** [comment]
> @AQ1991 what downloadable link? Could you share it to see if it fixes my issue?

Our server team was already using AWS on back end. They told me they had a function that returns a temporary link for the itme that we are requesting. So i just download the object on the fly.

**Comment by abiehusney25** [comment]
Is there a link to working dll's 
I placed the netstandard2.0 ones in the build, but I get the 3 errors:
The name 'UnityInitializer' does not exist in the current context
Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type
Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

Also this is for aws sns if that helps.

**Comment by zerozinczero** [comment]
@AQ1991 okay, I got it working on my end too. Glad we figured it out!

**Comment by zerozinczero** [comment]
@abiehusney25  There are a couple of links in this forum I think, but if those aren't working, you can try mine: https://drive.google.com/file/d/1RGpBO4mkKayUmNoQVmDwVxUQyBG4PY1v/view?usp=sharing

**Comment by abiehusney25** [comment]
@zerozinczero Thanks for the response but I used your dll AWSSDK.Core, and it is not working.

When I use the  Dll's that came with the UnitySDK [Found here](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html), and with the one you added the builds fails.
Failed to Build:
-     /gradleOut/unityLibrary/src/main/java/com/amazonaws/unity/Utils.java:11: error: cannot find symbol
-     location: class AWSUnityGCMWrapper
-     Temp/gradleOut/unityLibrary/src/main/java/com/amazonaws/unity/AWSUnityGCMWrapper.java uses or overrides a deprecated API.

This is for AWS SNS for Unity.
When I replace the dll's of sns,AWSSDK.SecurityToken, and some others, that I have found [here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/) I get compile errors. They are the new netstandard2.0 dll's.

-     The name 'UnityInitializer' does not exist in the current context
-     Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type
-     Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

**Comment by zerozinczero** [comment]
@abiehusney25 I don't know what SNS is, but my guess is the UnityInitalizer error may becaues you don't have script attached to a gameobject that calls this statement 

```
void Awake(){
		UnityInitializer.AttachToGameObject(gameObject);
		Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;
	}
```

I'm not sure about the lambda issue, but the two errors might be related.

**Comment by abiehusney25** [comment]
> @abiehusney25 I don't know what SNS is, but my guess is the UnityInitalizer error may becaues you don't have script attached to a gameobject that calls this statement
> 
> ```
> void Awake(){
> 		UnityInitializer.AttachToGameObject(gameObject);
> 		Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;
> 	}
> ```
> 
> I'm not sure about the lambda issue, but the two errors might be related.

It already has that code, and the error is under UnityInitializer.

Where did you get the aws dll's from? I originally got them from [Unity Aws website](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html) 

then replaced them with the new netstandard2.0 .dll's [As found here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/)

and get the compile error as seen above.

Where did you get the aws sdk that you are using in unity?

Thank you so much

**Comment by zerozinczero** [comment]
@abiehusney25 I was trying to get Amazon Polly working for Unity, and I found this thread to get the .dlls I needed. I'm not sure if that would work for you, but here is the link to the dlls https://aws-net-sdk.s3.amazonaws.com/preview/UnityPollySupport.3.3.2.4.zip

here is the thread btw, in case that helps too.

**Comment by abiehusney25** [comment]
> @abiehusney25 I was trying to get Amazon Polly working for Unity, and I found this thread to get the .dlls I needed. I'm not sure if that would work for you, but here is the link to the dlls https://aws-net-sdk.s3.amazonaws.com/preview/UnityPollySupport.3.3.2.4.zip
> 
> here is the thread btw, in case that helps too.

Sorry where is the thread.
And for the regular sdk I am getting gradle build failure;

CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/Hub/Editor/2019.3.0f6/PlaybackEngines/AndroidPlayer/OpenJDK/bin/java -classpath "/Applications/Unity/Hub/Editor/2019.3.0f6/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

  symbol:   class GoogleCloudMessaging
  location: class AWSUnityGCMWrapper
/Users/kodalabs/Desktop/DunkPunks2/Temp/gradleOut/unityLibrary/src/main/java/com/amazonaws/unity/AWSUnityGCMWrapper.java:26: error: cannot find symbol
			GoogleCloudMessaging gcm = GoogleCloudMessaging
			                           ^

**Comment by zerozinczero** [comment]
@abiehusney25  sorry about that, here is the link https://github.com/aws/aws-sdk-net/issues/627

and as far as the error, I have no idea what that could mean.... I would try googling it and if nothing pops up, try commenting out the code that uses GoogleCloud Messaging. This is Amazon code, so it seems strange that it needs to use Google, so you may be able to make a build without it.

**Comment by abiehusney25** [comment]
@zerozinczero Thank you so much for getting back to me but I dont know what is going on.

I am trying a brand new build: Unity 2019.3. (it can build apk's no problem)
I download the latest aws sdk aws-sdk-unity_3.3.670.0 from [here](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html)
Import the AWSSDK.SimpleNotificationService.3.3.101.117.unitypackage into Unity.
After making the proper link.xml and androidmanifest files and placing them in the proper places, it fails to build. 

This is for ILCCP. And I have replaced the AWSSDK.Core.dll file that you have sent.

Am I using the sdk as linked to above, is there a newer one, or something else I should use that I am not seeing. 

Thank you very much

**Comment by zerozinczero** [comment]
@abiehusney25 are you still getting the same error?

By the way what are you trying to do in this project? Maybe there's a solution besides AWS?

As far as what to do next, I would try a mono build instead of a ILCpp, just to see if it helps. I would also download jetbrains dotpeek to unpack the .dll files and see what's missing or isn't needed ( I had that problem with iOS code being used for Android).

**Comment by abiehusney25** [comment]
> @abiehusney25 are you still getting the same error?
> 
> By the way what are you trying to do in this project? Maybe there's a solution besides AWS?
> 
> As far as what to do next, I would try a mono build instead of a ILCpp, just to see if it helps. I would also download jetbrains dotpeek to unpack the .dll files and see what's missing or isn't needed ( I had that problem with iOS code being used for Android).
@zerozinczero 
Yes I am getting the same error. I get the same error with both ILCPP and Mono.

This is for push notifications for my app,using AWS SimpleNotificationService.

Can you export your unity into a package that just has the aws inside it, so I could make sure I am using the correct sdk? or do you have a link to the sdk you are using?

**Comment by zerozinczero** [comment]
@abiehusney25 

I'm not sure if this would meet your needs, but Unity has a notification package that should be able to send notifications too. It may be worth trying or possibly easier instead of AWS. Here's a link https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0/manual/index.html 

I can't export my project since it's at work and I'm home for the weekend. However, try using Jetbrains dotpeek to look at the c# projects inside. Right click on those projects and make sure the build output type is set to Unity 3.5 something ( I don't remember the exact language off-hand) instead of net standard 2.0. Once you rebuild the project's .dll, try replacing the old .dll with the new ones.

**Comment by marcusice** [comment]
If you can't build the dll for unity2019 yourself, you may download the dll here:
https://lhkmarcus.com/2020/04/05/how-to-use-aws-sdk-in-unity-2019/

**Comment by Thaina** [comment]
Seem like I get the same problem in unity 2020 too

**Comment by notpresleybutelvis** [comment]
@daltonmachado @marcusice Thanks for fixing this. Had I not seen this issue, we would be stuck in our development. I sincerely ask the developers at AWS to pay heed to user requests and not brush them aside like this. People are genuinely posting about issues, don't mark them as duplicates or ask them questions like have you implemented this link.

You need to realize you are developing your SDK using Unity 5, it's legacy. Also, if your code works you check on the PC or Mac, not on the mobile device, the users here are complaining about not working on mobile device.

**Comment by marcusice** [comment]
Still a lot of views about this issue.
You may watch this video to solve that step by step:
[https://youtu.be/uRNUJzQzNTk](https://youtu.be/uRNUJzQzNTk)

**Comment by monkeyMax-SVG** [comment]
@marcusice so great. 
it solved my issue
Thank you.

**Comment by ashishdhingra** [comment]
Hi @daltonmachado,

I see lot of comments on this issue. Please review is this is still an issue or if this could be closed.

Thanks,
Ashish

**Comment by johnboiles** [comment]
I just ran into this issue on Unity 2019.4. @marcusice's fix solved things for me. So yes, definitely still an issue.

**Comment by daltonmachado** [comment]
> Hi @daltonmachado,
> 
> I see lot of comments on this issue. Please review is this is still an issue or if this could be closed.
> 
> Thanks,
> Ashish

Hi @ashishdhingra . It should be closed according to [this comment](https://github.com/aws/aws-sdk-net/pull/1295#issuecomment-591038489) on my PR (which was closed some time ago).

**Comment by johnboiles** [comment]
If the AWS Unity SDK is deprecated it would be great to have the [docs](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/what-is-unity-plugin.html) updated so that people don't waste their time with it.
