### ISSUE TITLE
Remove platform-specific code in favor of .NET Standard 2.0

### ISSUE THREAD

**Issue by costleya** [aws/aws-sdk-net#1348]
Remove platform specific code for:
* Xamarin
* Windows Phone
* UWP
* Unity

In favor of providing .NET Standard 2.0 implementations.

**Comment by damianh** [comment]
I've attempted to contribute to this repo several times and been stopped in my tracks with the sheer complexity of the number of solutions, projects and 'weight'. This is going to be so much better!

**Comment by NGL321** [comment]
@normj is this an issue we can close?

**Comment by hunanniu** [comment]
Discussed on Friday, this has been addressed

**Comment by damianh** [comment]
@hunanniu what was the outcome of the discussion / decision? I still see lots of net35/net45 csproj files in the repo.
