### ISSUE TITLE
Can't set USEast1RegionalEndpointValue property of AmazonS3Config due to an exception in the constructor.

### ISSUE THREAD

**Issue by mhdejonge** [aws/aws-sdk-net#1490]
AmazonS3Config inherits ClientConfig which calls the virtual Initialize method. AmazonS3Config overrides Initialize and calls UpdateEndpointForUsEast1Regional. So users of the AmazonS3Config class don't have a chance to set the USEast1RegionalEndpointValue property before UpdateEndpointForUsEast1Regional is called.
## Expected Behavior

This is what I want to do, but currently new AmazonS3Config() throws an exception.
```
var awsCredentials = new BasicAWSCredentials("MyAccessKey", "MySecretKey");

var amazonS3Config = new AmazonS3Config();
amazonS3Config.RegionEndpoint = RegionEndpoint.USEast1;
amazonS3Config.USEast1RegionalEndpointValue = S3UsEast1RegionalEndpointValue.Regional;

var amazonS3Client = new AmazonS3Client(awsCredentials, amazonS3Config);
```
## Current Behavior

My company has our own secret management system so we don't use the AWS SDK credential manager. We also run our websites as a network service if that makes a difference. When creating an instance of AmazonS3Config we get the following error.
```
System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.Settings.PersistenceManager' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Amazon.Runtime.Internal.Settings.PersistenceManager..cctor()
   --- End of inner exception stack trace ---
   at Amazon.Util.Internal.SettingsManager.GetSettings()
   at Amazon.Util.Internal.SettingsManager.TryGetObjectByProperty(String propertyName, String value, String& uniqueKey, Dictionary`2& properties)
   at Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.S3.AmazonS3Config.CheckCredentialsFile()
   at Amazon.S3.AmazonS3Config.GetEndpointFlagValueForUsEast1Regional()
   at Amazon.S3.AmazonS3Config.UpdateEndpointForUsEast1Regional()
   at Amazon.S3.AmazonS3Config.Initialize()
   at Amazon.Runtime.ClientConfig..ctor()
   at Amazon.S3.AmazonS3Config..ctor()
```
## Possible Solution

Remove the call to UpdateEndpointForUsEast1Regional from Initialize. Maybe call it from the constructor of AmazonS3Client instead. Adding a try/catch block could also solve the issue.
## Steps to Reproduce (for bugs)

Restrict access to the path that credential files are stored in. Then run the code snippet from the Expected Behavior section. When run on our Windows servers under the Network Service user the sdk tries to go to this path: "C:\Windows\system32\config\systemprofile".
## Context

I want to set the USEast1RegionalEndpointValue property in code so the sdk doesn't try to fetch it from a file or environment variable, because we don't have that set up.
## Your Environment

* AWSSDK.Core version used: 3.3.104.7
* AWSSDK.S3 version used: 3.3.110.2
* .NET Core version used: 2.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks for the feedback.  We're looking into it.

**Comment by SrutiG** [comment]
I am working on this issue and I think I have identified the root cause. However, I am still having trouble reproducing it. Will update this ticket with my progress.

**Comment by mhdejonge** [comment]
I came up with a solid work-around, but a solution would still be appreciated.
```
namespace Example
{
    using Amazon;
    using Amazon.Runtime;
    using Amazon.S3;

    public class MyAmazonS3Config : AmazonS3Config
    {
        public MyAmazonS3Config()
        {
            RegionEndpoint = RegionEndpoint.USEast1;
            base.Initialize();
        }

        protected override void Initialize()
        {
            USEast1RegionalEndpointValue = S3UsEast1RegionalEndpointValue.Regional;
        }
    }
}
```

**Comment by SrutiG** [comment]
The latest version of AWSSDK.S3 should address this issue. It moves the logic for checking the credentials file away from the Initialize method.

**Comment by mhdejonge** [comment]
Thank you. I installed the latest version and things are working as expected.

**Comment by jjrutter** [comment]
What release version will this fix be included in ? We are also having this issue after updating to 
AWSSDK.Core 3.3.104.21
AWSSDK.S3 3.3.110.19
, and looks like this issue is a duplicate
#1519 
https://github.com/aws/aws-sdk-net/issues/1519

**Comment by SrutiG** [comment]
@jjrutter Sorry for the delayed response. This issue should have been addressed in AWSSDK.S3 3.3.110.17. Could you provide some more details? Are you setting USEast1RegionalEndpointValue explicitly in the code? Are you also getting a System.UnauthorizedAccessException?

**Comment by iongritco-sv** [comment]
I still have the exact same issue with version 3.3.110.50. I'm using .NET Core 3.1. 
The error message that I receive:
Error message:
System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception.
---> System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.Settings.PersistenceManager' threw an exception.
---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile' is denied.
at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
at System.IO.Directory.CreateDirectory(String path)
at Amazon.Runtime.Internal.Settings.PersistenceManager..cctor()
--- End of inner exception stack trace ---
at Amazon.Runtime.Internal.Settings.PersistenceManager.get_Instance()
at Amazon.Util.Internal.SettingsManager.GetSettings()
at Amazon.Util.Internal.SettingsManager.TryGetObjectByProperty(String propertyName, String value, String& uniqueKey, Dictionary2& properties) at Amazon.Util.Internal.NamedSettingsManager.TryGetObject(String displayName, String& uniqueKey, Dictionary2& properties)
at Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)
at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)
at Amazon.Runtime.Internal.ProfileInternalConfiguration..ctor(ICredentialProfileSource source)
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()
--- End of inner exception stack trace ---
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.get_RetryMode()
at Amazon.Runtime.ClientConfig.get_RetryMode()
at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
at Amazon.Runtime.AmazonServiceClient..ctor(String awsAccessKeyId, String awsSecretAccessKey, ClientConfig config)
at Amazon.S3.AmazonS3Client..ctor(String awsAccessKeyId, String awsSecretAccessKey, AmazonS3Config clientConfig)
at AmazonStorage.AmazonStorageService.GetAmazonS3Client()

Are there any workarounds for this issue?

Thank you!

**Comment by iongritco-sv** [comment]
Just for reference, this is the code that I'm using:

```
var amazonS3Config = new AmazonS3Config
                                 {
                                    RegionEndpoint = RegionEndpoint.USEast1
                                 };
var amazonClient = new AmazonS3Client(_options.AwsAccessKeyId, _options.AwsSecretAccess, amazonS3Config) 
```

@SrutiG could you take a look please?

Thank you

**Comment by mhdejonge** [comment]
@iongritco-sv you need to also set the USEast1RegionalEndpointValue property of AmazonS3Config.
```
var amazonS3Config = new AmazonS3Config
{
    RegionEndpoint = RegionEndpoint.USEast1,
    USEast1RegionalEndpointValue = S3UsEast1RegionalEndpointValue.Regional
};
// or use the legacy value: S3UsEast1RegionalEndpointValue.Legacy
```

**Comment by iongritco-sv** [comment]
Thanks for the reply @mhdejonge 
In my case this workaround doesn't work, I get the same error.
The only solution that worked is to downgrade the package to version 3.3.109.4

**Comment by JankiSayta13** [comment]
I have same issue and it is still there even after 
Downgrade AWSSDK to 3.3.109.4

**Comment by btecu** [comment]
@SrutiG this is still broken. For that matter, you don't even have to upgrade `AWSSDK.S3` past `3.3.31.*`, is enough to upgrade `AWSSDK.Core` to latest version. It seems that `3.3.104.38` is the latest version that actually works.

**Comment by JankiSayta13** [comment]
I was using multiple AWSSDK references and only Downgraded s3 reference which leads to error but If you downgrade all references with AWSSDK  to 3.3.109.4 works fine for me

**Comment by SrutiG** [comment]
@iongritco-sv @JankiSayta13 @btecu Sorry to hear that the previous patch did not fix the issues. Try using the latest version of Core, 3.3.106.20. This version specifically addresses the Persistence Manager issues and blocks it from accessing a credential file when running under a service role. Hope this solves it for everyone, and please let us know if you continue to experience problems. The best way to do this is to open a new issue so it can be quickly brought to our attention. Thanks!

**Comment by dssagar93** [comment]
For me on IIS, I had to turn on Load User Profile under the pool. It solved the issue.
